version: '3.3'
services:
  db:
    image: postgres:14.1
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./tenpo-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - database.env
  app:
    image: diegosaez/tenpo_challenge:1.0
    depends_on: 
      - db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tenpo?currentSchema=challenge      
    ports:
      - 8080:8080            